### ISSUE TITLE
Does not compile for MIPS targets

### ISSUE THREAD

**Issue by raphaelcohn** [nathan7/libvalgrind#3]
On a Mac OS X El Capitan machine, using libfringe as a dependency (which depends on libvalgrind_request), Rust nightly as of today:-

cargo build -j 1 --target=mipsel-unknown-linux-musl (or cargo build -j 1 --target=mips-unknown-linux-musl) produces:-

``` bash
error[E0432]: unresolved import `self::imp::Value`
 --> /Users/raph/.cargo/registry/src/github.com-1ecc6299db9ec823/valgrind_request-1.1.0/src/arch/mod.rs:1:21
  |
1 | pub use self::imp::{Value, do_client_request};
  |                     ^^^^^ Could not find `imp` in `arch`

error[E0432]: unresolved import `self::imp::do_client_request`
 --> /Users/raph/.cargo/registry/src/github.com-1ecc6299db9ec823/valgrind_request-1.1.0/src/arch/mod.rs:1:28
  |
1 | pub use self::imp::{Value, do_client_request};
  |                            ^^^^^^^^^^^^^^^^^ Could not find `imp` in `arch`

error: aborting due to 2 previous errors

error: Could not compile `valgrind_request`.
```

If MIPS isn't supported, that's fine, but it'd be nice to get a clear reason - perhaps a build script that panics?

**Comment by edef1c** [comment]
We plain don't have MIPS support yet. I can trivially add MIPS support to `libvalgrind_request`, but porting `libfringe` to MIPS would be a somewhat larger undertaking.

**Comment by raphaelcohn** [comment]
OK, I understand. As rust adds more supported CPU types, I can see it becoming more of a burden to maintain `libfringe` and its related dependencies (we now have CPU support for powerpc, powerpc64, s390x, mips, mips64, x86, x86_64, arm and aarch). It'd be great to have mips and mips64, simply because of their widespread use in the router and embedded space.

Adding CPU support for the slightly less common ones might make a good GSoC project.
